### ISSUE TITLE
Compatible with Meteor 0.7.0.1?

### ISSUE THREAD

**Issue by jcchin** [AlexeyMK/meteor-download#1]
Hi! This script worked like a charm the first time I tried it, unfortunately it seems broken now. Did Meteor 0.7.0.1 possibly break it, or is it just me?

**Comment by AlexeyMK** [comment]
Haven't tried yet!  Will take a look in the next few days, if nobody has a
chance to take a look earlier.

**Comment by AlexeyMK** [comment]
What sort of error message or output do you see?

**Comment by jcchin** [comment]
Thanks for the quick response! I see the warning halfway down, but no idea
how to fix it. Here's the output:

---

Starting to download from server

(if your deployment has a password, it will be needed here)

---

[redacted]

rm: /tmp/meteor-download.mongodump: No such file or directory

connected to: production-db-b3.meteor.io:27017

assertion: 18 { code: 18, ok: 0.0, errmsg: "auth fails" }

---

Uploading DB into your local meteor instance

---

starting local version of mongo db daemon

Mon Jan 13 02:27:53.357 [initandlisten] MongoDB starting : pid=85289
port=3002 dbpath=./.meteor/local/db 64-bit host=Jeffs-MacBook-Pro.local

Mon Jan 13 02:27:53.357 [initandlisten]

Mon Jan 13 02:27:53.357 [initandlisten] *\* WARNING: soft rlimits too low.
Number of files is 256, should be at least 1000

Mon Jan 13 02:27:53.357 [initandlisten] db version v2.4.8

Mon Jan 13 02:27:53.357 [initandlisten] git version:
51ea0c0eda7db5ec443192fc0467d1b26dee144e

Mon Jan 13 02:27:53.357 [initandlisten] build info: Darwin meteor.local
11.4.0 Darwin Kernel Version 11.4.0: Mon Apr  9 19:32:15 PDT 2012;
root:xnu-1699.26.8~1/RELEASE_X86_64 x86_64 BOOST_LIB_VERSION=1_49

Mon Jan 13 02:27:53.357 [initandlisten] allocator: tcmalloc

Mon Jan 13 02:27:53.357 [initandlisten] options: { bind_ip: "127.0.0.1",
dbpath: "./.meteor/local/db", nohttpinterface: true, port: 3002,
smallfiles: true }

Mon Jan 13 02:27:53.358 [initandlisten] journal
dir=./.meteor/local/db/journal

Mon Jan 13 02:27:53.358 [initandlisten] recover : no journal files present,
no recovery needed

Mon Jan 13 02:27:53.374 [initandlisten]

Mon Jan 13 02:27:53.374 [initandlisten] *\* WARNING: mongod started without
--replSet yet 1 documents are present in local.system.replset

Mon Jan 13 02:27:53.374 [initandlisten] *\*          Restart with --replSet
unless you are doing maintenance and no other clients are connected.

Mon Jan 13 02:27:53.374 [initandlisten] *\*          The TTL collection
monitor will not start because of this.

Mon Jan 13 02:27:53.374 [initandlisten] *\*          For more info see
http://dochub.mongodb.org/core/ttlcollections

Mon Jan 13 02:27:53.374 [initandlisten]

Mon Jan 13 02:27:53.385 [initandlisten] waiting for connections on port 3002

connected to: localhost:3002

Mon Jan 13 02:27:55.438 [initandlisten] connection accepted from
127.0.0.1:49720 #1 (1 connection now open)

Mon Jan 13 02:27:55.438 ERROR: don't know what to do with file
[/tmp/meteor-download.mongodump/pushplan_meteor_com/]

Mon Jan 13 02:27:55.441 [conn1] end connection 127.0.0.1:49720 (0
connections now open)

Mon Jan 13 02:27:55.442 [signalProcessingThread] got signal 15 (Terminated:
15), will terminate after current cmd ends

Mon Jan 13 02:27:55.442 [signalProcessingThread] now exiting

Mon Jan 13 02:27:55.442 dbexit:

Mon Jan 13 02:27:55.442 [signalProcessingThread] shutdown: going to close
listening sockets...

Mon Jan 13 02:27:55.442 [signalProcessingThread] closing listening socket:
10

Mon Jan 13 02:27:55.442 [signalProcessingThread] closing listening socket:
11

Mon Jan 13 02:27:55.442 [signalProcessingThread] removing socket file:
/tmp/mongodb-3002.sock

Mon Jan 13 02:27:55.443 [signalProcessingThread] shutdown: going to flush
diaglog...

Mon Jan 13 02:27:55.443 [signalProcessingThread] shutdown: going to close
sockets...

Mon Jan 13 02:27:55.443 [signalProcessingThread] shutdown: waiting for fs
preallocator...

Mon Jan 13 02:27:55.443 [signalProcessingThread] shutdown: lock for final
commit...

Mon Jan 13 02:27:55.443 [signalProcessingThread] shutdown: final commit...

Mon Jan 13 02:27:55.452 [signalProcessingThread] shutdown: closing all
files...

Mon Jan 13 02:27:55.452 [signalProcessingThread] closeAllFiles() finished

Mon Jan 13 02:27:55.452 [signalProcessingThread] journalCleanup...

Mon Jan 13 02:27:55.452 [signalProcessingThread] removeJournalFiles

Mon Jan 13 02:27:55.452 [signalProcessingThread] shutdown: removing fs
lock...

Mon Jan 13 02:27:55.452 dbexit: really exiting now

[1]+  Done                    ~/.meteor/tools/latest/mongodb/bin/mongod
--bind_ip 127.0.0.1 --smallfiles --nohttpinterface --port 3002 --dbpath
./.meteor/local/db

---

All done, enjoy!

---

**Comment by AlexeyMK** [comment]
Just pushed an update which fixed the 0.7.0 issue (the username is no longer just _client_) and added a few other safety checks. Try the latest version!

**Comment by jcchin** [comment]
hrmmm, downloaded the new script, I'm still getting the same error.

``` terminal
-----------------------------------------------------------
Starting to download from server
(if your deployment has a password, it will be needed here)
-----------------------------------------------------------
mongodb://client-24589d67:52b743cc-7ac4-dd07-24ba-530ad180bbbe@production-db-b3.meteor.io:27017/pushplan_meteor_com
rm: /tmp/meteor-download.mongodump: No such file or directory
connected to: production-db-b3.meteor.io:27017
Tue Jan 14 20:04:35.362 DATABASE: pushplan_meteor_com    to     dump/pushplan_meteor_com
Tue Jan 14 20:04:35.423     pushplan_meteor_com.system.indexes to dump/pushplan_meteor_com/system.indexes.bson
Tue Jan 14 20:04:35.508          16 objects
Tue Jan 14 20:04:35.512     pushplan_meteor_com.system.users to dump/pushplan_meteor_com/system.users.bson
Tue Jan 14 20:04:35.573          2 objects
Tue Jan 14 20:04:35.573     Metadata for pushplan_meteor_com.system.users to dump/pushplan_meteor_com/system.users.metadata.json
Tue Jan 14 20:04:35.574     pushplan_meteor_com.users to dump/pushplan_meteor_com/users.bson
Tue Jan 14 20:04:35.730          81 objects
Tue Jan 14 20:04:35.730     Metadata for pushplan_meteor_com.users to dump/pushplan_meteor_com/users.metadata.json
Tue Jan 14 20:04:35.731     pushplan_meteor_com.meteor_accounts_loginServiceConfiguration to dump/pushplan_meteor_com/meteor_accounts_loginServiceConfiguration.bson
Tue Jan 14 20:04:35.789          2 objects
Tue Jan 14 20:04:35.789     Metadata for pushplan_meteor_com.meteor_accounts_loginServiceConfiguration to dump/pushplan_meteor_com/meteor_accounts_loginServiceConfiguration.metadata.json
Tue Jan 14 20:04:35.789     pushplan_meteor_com.huddles to dump/pushplan_meteor_com/huddles.bson
Tue Jan 14 20:04:35.988          55 objects
Tue Jan 14 20:04:35.988     Metadata for pushplan_meteor_com.huddles to dump/pushplan_meteor_com/huddles.metadata.json
Tue Jan 14 20:04:35.988     pushplan_meteor_com.ideas to dump/pushplan_meteor_com/ideas.bson
Tue Jan 14 20:04:36.298          1591 objects
Tue Jan 14 20:04:36.298     Metadata for pushplan_meteor_com.ideas to dump/pushplan_meteor_com/ideas.metadata.json
Tue Jan 14 20:04:36.299     pushplan_meteor_com.notify to dump/pushplan_meteor_com/notify.bson
Tue Jan 14 20:04:36.465          378 objects
Tue Jan 14 20:04:36.465     Metadata for pushplan_meteor_com.notify to dump/pushplan_meteor_com/notify.metadata.json
-----------------------------------------------------------
Uploading DB into your local meteor instance
-----------------------------------------------------------
starting local version of mongo db daemon
Tue Jan 14 20:04:36.519 [initandlisten] MongoDB starting : pid=92878 port=3002 dbpath=./.meteor/local/db 64-bit host=Jeffs-MacBook-Pro.local
Tue Jan 14 20:04:36.519 [initandlisten] 
Tue Jan 14 20:04:36.519 [initandlisten] ** WARNING: soft rlimits too low. Number of files is 256, should be at least 1000
Tue Jan 14 20:04:36.519 [initandlisten] db version v2.4.8
Tue Jan 14 20:04:36.519 [initandlisten] git version: 51ea0c0eda7db5ec443192fc0467d1b26dee144e
Tue Jan 14 20:04:36.519 [initandlisten] build info: Darwin meteor.local 11.4.0 Darwin Kernel Version 11.4.0: Mon Apr  9 19:32:15 PDT 2012; root:xnu-1699.26.8~1/RELEASE_X86_64 x86_64 BOOST_LIB_VERSION=1_49
Tue Jan 14 20:04:36.519 [initandlisten] allocator: tcmalloc
Tue Jan 14 20:04:36.519 [initandlisten] options: { bind_ip: "127.0.0.1", dbpath: "./.meteor/local/db", nohttpinterface: true, port: 3002, smallfiles: true }
Tue Jan 14 20:04:36.519 [initandlisten] journal dir=./.meteor/local/db/journal
Tue Jan 14 20:04:36.519 [initandlisten] recover : no journal files present, no recovery needed
Tue Jan 14 20:04:36.535 [initandlisten] 
Tue Jan 14 20:04:36.535 [initandlisten] ** WARNING: mongod started without --replSet yet 1 documents are present in local.system.replset
Tue Jan 14 20:04:36.536 [initandlisten] **          Restart with --replSet unless you are doing maintenance and no other clients are connected.
Tue Jan 14 20:04:36.536 [initandlisten] **          The TTL collection monitor will not start because of this.
Tue Jan 14 20:04:36.536 [initandlisten] **          For more info see http://dochub.mongodb.org/core/ttlcollections
Tue Jan 14 20:04:36.536 [initandlisten] 
Tue Jan 14 20:04:36.547 [initandlisten] waiting for connections on port 3002
connected to: localhost:3002
Tue Jan 14 20:04:38.602 [initandlisten] connection accepted from 127.0.0.1:54256 #1 (1 connection now open)
Tue Jan 14 20:04:38.602 ERROR: don't know what to do with file [/tmp/meteor-download.mongodump//]
Tue Jan 14 20:04:38.606 [conn1] end connection 127.0.0.1:54256 (0 connections now open)
Tue Jan 14 20:04:38.607 [signalProcessingThread] got signal 15 (Terminated: 15), will terminate after current cmd ends
Tue Jan 14 20:04:38.607 [signalProcessingThread] now exiting
Tue Jan 14 20:04:38.607 dbexit: 
Tue Jan 14 20:04:38.607 [signalProcessingThread] shutdown: going to close listening sockets...
Tue Jan 14 20:04:38.607 [signalProcessingThread] closing listening socket: 10
Tue Jan 14 20:04:38.607 [signalProcessingThread] closing listening socket: 11
Tue Jan 14 20:04:38.608 [signalProcessingThread] removing socket file: /tmp/mongodb-3002.sock
Tue Jan 14 20:04:38.608 [signalProcessingThread] shutdown: going to flush diaglog...
Tue Jan 14 20:04:38.608 [signalProcessingThread] shutdown: going to close sockets...
Tue Jan 14 20:04:38.608 [signalProcessingThread] shutdown: waiting for fs preallocator...
Tue Jan 14 20:04:38.608 [signalProcessingThread] shutdown: lock for final commit...
Tue Jan 14 20:04:38.608 [signalProcessingThread] shutdown: final commit...
Tue Jan 14 20:04:38.614 [signalProcessingThread] shutdown: closing all files...
Tue Jan 14 20:04:38.614 [signalProcessingThread] closeAllFiles() finished
Tue Jan 14 20:04:38.614 [signalProcessingThread] journalCleanup...
Tue Jan 14 20:04:38.614 [signalProcessingThread] removeJournalFiles
Tue Jan 14 20:04:38.615 [signalProcessingThread] shutdown: removing fs lock...
Tue Jan 14 20:04:38.615 dbexit: really exiting now
[1]+  Done                    ~/.meteor/tools/latest/mongodb/bin/mongod --bind_ip 127.0.0.1 --smallfiles --nohttpinterface --port 3002 --dbpath ./$METEOR_LOCAL_DB
-----------------------------------------------------------
All done, enjoy!
-----------------------------------------------------------
```

**Comment by AlexeyMK** [comment]
Looks to me like things worked.  The `rm` is not really an error, it's just
deleting a temp file that may or may not be there.

**Comment by jcchin** [comment]
It left a "dump" folder in my project, which appears to have the database contents in it, but I can't access it from my local instance. My understanding of mongo is very minimal, am I missing something obvious?

**Comment by jcchin** [comment]
there is a .bson and .json file in the dump folder for each of my collections, do I need to point mongo to these files somehow?

**Comment by AlexeyMK** [comment]
You're totally right. For now, move the contents of the dump directory to ./.meteor/local/db.  I'm figuring out why this is happening.

**Comment by AlexeyMK** [comment]
Give it a try now - when I rewrote the regexes, some formerly useful variables got lost. Should work.

**Comment by jcchin** [comment]
works great! Thanks so much for your help!
