### ISSUE TITLE
zsh: exec format error: ./download.sh

### ISSUE THREAD

**Issue by ndemoreau** [AlexeyMK/meteor-download#4]
Hi,

when I run your script, I get this error:
zsh: exec format error: ./download.sh
Originally, I had a permission denied
Then I made a chmod 755 but now I get this format error.

Any Idea how to solve it?
Is it compatible with meteor 1.0?

Thanks.

**Comment by AlexeyMK** [comment]
Howdy! Yup, the script is meteor 1.0 compatible. My guess is this is a zsh issue, since I only tested with bash.  Have you tried running the script via `sh download.sh <arguments>`?

**Comment by ndemoreau** [comment]
I just tried that:

sh download.sh aerts.meteor.com

I get no error but nothing seems to happen. It goes right to the next
prompt.

I'm trying to find a way to run bash without totally uninstalling zsh but
no luck until now. I'm pretty bad at all this command line stuff...

On Tue, Jan 6, 2015 at 2:27 PM, Alexey Komissarouk <notifications@github.com

> wrote:
> 
> Howdy! Yup, the script is meteor 1.0 compatible. My guess is this is a zsh
> issue, since I only tested with bash. Have you tried running the script via sh
> download.sh <arguments>?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/AlexeyMK/meteor-download/issues/4#issuecomment-68864634
> .

## 

---

_Nicolas de Moreau_

M: +32 (0)475 614 700
@: nicolas@demoreau.be
Twitter: ndemoreau
Skype: ndemoreau

Leuvensebaan 52
B-3040 Ottenburg – Belgium

**Comment by AlexeyMK** [comment]
Heh, it happens. Even though you are running zsh, if you start the command
with `sh`, then you are using the shell prompt (the most basic one) to run
the script, which should work out. I recommend putting a bunch of "echo"
statements in the code and debugging to see what happens.

Just to check - are you on OS X?

**Comment by ndemoreau** [comment]
OK, I'll try that.

Yes, I'm on OS X.

Thank you!

On Tue, Jan 6, 2015 at 4:37 PM, Alexey Komissarouk <notifications@github.com

> wrote:
> 
> Heh, it happens. Even though you are running zsh, if you start the command
> with `sh`, then you are using the shell prompt (the most basic one) to run
> the script, which should work out. I recommend putting a bunch of "echo"
> statements in the code and debugging to see what happens.
> 
> Just to check - are you on OS X?
> 
> On Tue, Jan 6, 2015 at 3:39 PM, ndemoreau notifications@github.com
> wrote:
> 
> > I just tried that:
> > 
> > sh download.sh aerts.meteor.com
> > 
> > I get no error but nothing seems to happen. It goes right to the next
> > prompt.
> > 
> > I'm trying to find a way to run bash without totally uninstalling zsh
> > but
> > no luck until now. I'm pretty bad at all this command line stuff...
> > 
> > On Tue, Jan 6, 2015 at 2:27 PM, Alexey Komissarouk <
> > notifications@github.com
> > 
> > > wrote:
> > > 
> > > Howdy! Yup, the script is meteor 1.0 compatible. My guess is this is a
> > > zsh
> > > issue, since I only tested with bash. Have you tried running the
> > > script
> > > via sh
> > > download.sh <arguments>?
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> > 
> > https://github.com/AlexeyMK/meteor-download/issues/4#issuecomment-68864634>
> > 
> > > .
> > 
> > ## 
> > 
> > ---
> > 
> > _Nicolas de Moreau_
> > 
> > M: +32 (0)475 614 700
> > @: nicolas@demoreau.be
> > Twitter: ndemoreau
> > Skype: ndemoreau
> > 
> > Leuvensebaan 52
> > B-3040 Ottenburg – Belgium
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/AlexeyMK/meteor-download/issues/4#issuecomment-68865802>
> > 
> > .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/AlexeyMK/meteor-download/issues/4#issuecomment-68880872
> .

## 

---

_Nicolas de Moreau_

M: +32 (0)475 614 700
@: nicolas@demoreau.be
Twitter: ndemoreau
Skype: ndemoreau

Leuvensebaan 52
B-3040 Ottenburg – Belgium

**Comment by ndemoreau** [comment]
While trying to add echos, I discovered that download.sh add been downloaded empty... I copy-pasted the content and now it works like a charm... Thanks for your help!
